import = [
	'~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml',
]

# FOR WINDOWS: Mannauly install nerd font and set to this terminal
[font]
normal = { family = "DroidSansM Nerd Font Propo", style = "Regular" }
size = 18

[keyboard]
bindings = [
	{ key = "Z", mods = "Control|Shift", action = "ToggleFullscreen" },
	#{ key = "C", mods = "Control|Shift", action = "CreateNewWindow" },
]

[shell]
program = "tmux"
#program = "wsl --cd ~ --exec tmux" # FOR WINDOWS

[window]
decorations = "None" # no top bar
startup_mode = "Fullscreen" # Maximize/Fullscreen when startup
#startup_mode = "Maximized" # FOR WINDOWS
